### ISSUE TITLE
Eos Classic

### ISSUE THREAD

**Issue by acathon** [minerpoolnet/pools#90]
Hello, 
We have launched a new pool for a new born (9/june/2018) coin named EOSC based on daggerhashimoto algo.
So I think it's better if it's possible to make a new pools list for this coin ! 

check out http://eosc.methpool.com
thanks .

**Comment by ghost** [comment]
It seems that it is just a copy of ETH with EOS brand name attached.
https://github.com/EthereumCommonwealth/etherwallet/pull/162

**Comment by ghost** [comment]
@kimmyeonghun So you are trolling all over around 😄
